"""Rebuilds assets.js from the files in assets/. Run: python tools/build_assets.py
assets.js embeds the brand images as data URIs so the page (and the team-card export) works on any host."""
import base64, os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
def uri(name, mime):
    with open(os.path.join(root, 'assets', name), 'rb') as f:
        return f'data:{mime};base64,' + base64.b64encode(f.read()).decode()
js = ("/* Generated by tools/build_assets.py. Do not edit by hand. */\n"
      "window.ASSETS={wordmark:'%s',gdg:'%s',formqr:'%s'};\n") % (
      uri('hackober-wordmark.webp', 'image/webp'), uri('gdg-lockup.webp', 'image/webp'), uri('feedback-qr.png', 'image/png'))
with open(os.path.join(root, 'assets.js'), 'w') as f: f.write(js)
print('assets.js written,', len(js) // 1024, 'KB')
